-- Complete the Education & Tuition filter master data so GET /api/tuition/filters returns a real
-- subjects/levels list instead of empty arrays, across the whole tuition vertical (education-tuition
-- and all of its direct children), not just School Tuition.
--
-- Root cause of the empty subjects/levels (see TuitionFilterMetadataService): `subject` and
-- `grade` were seeded as dataType TEXT (free text), so attribute_options - the table the filter
-- endpoint reads - never had any rows for them. Master-data/configuration only: no schema changes,
-- no new tables/columns, no edits to already-applied migrations (V1-V9). ad_attribute_values.value_text
-- is a plain varchar shared by TEXT and SELECT alike, so flipping data_type to SELECT does not
-- touch or corrupt any stored ad value.
--
-- Existing free-text ad_attribute_values are preserved as-is; none are rewritten by this migration.
-- Two free-text values used by seeded ads ("Combined Mathematics", "Spoken English") would not have
-- matched the new canonical SELECT values case-insensitively (matchOption() in AdAttributeService
-- does not normalize whitespace/punctuation), so LocalDataSeeder's own seed data (not production ad
-- data) was updated separately to use the canonical values (COMBINED_MATHEMATICS, SPOKEN_ENGLISH,
-- OL, AL, PRIMARY) - see LocalDataSeeder#tuitionAdSeeds. No real ad content is touched by this file.
--
-- curriculum/classMode stable *values* are intentionally left untouched (LOCAL, EDEXCEL, CAMBRIDGE,
-- IB, PROFESSIONAL, PHYSICAL, ONLINE, BOTH) to preserve any existing ad_attribute_values - only
-- labels/display_order/required are corrected, and BOTH keeps its existing "Online & Physical"
-- label (Option A from the task) rather than being renamed, so no ad using BOTH is affected.
--
-- Per-category (not root-level) subject/grade/classMode definitions are intentional, not
-- unnecessary duplication: AdAttributeService.buildValues resolves attribute definitions strictly
-- by the ad's own leaf category id with no ancestor-chain inheritance (unlike the generic
-- /api/categories/{slug}/filters endpoint, which does inherit from ancestors for search-filter
-- display only). A single root-level definition on education-tuition would be invisible to Post Ad
-- validation for every leaf category, so per-category definitions are what "the existing
-- architecture absolutely requires" here. Changing AdAttributeService to support inherited
-- definitions would affect posting for every category in the marketplace, not just tuition, which
-- is out of scope for this master-data-only task.

-- ============================================================================
-- 1. Convert subject/grade from TEXT to SELECT so they can carry attribute_options.
--    value_text storage is identical between TEXT and SELECT, so this is a metadata-only change.
-- ============================================================================
UPDATE attribute_definitions SET data_type = 'SELECT'
WHERE data_type = 'TEXT' AND attribute_key = 'subject'
  AND category_id IN (SELECT id FROM categories WHERE slug IN
      ('school-tuition', 'music', 'dancing', 'drama-theatre', 'art-creative-classes', 'technology-coding'));

UPDATE attribute_definitions SET data_type = 'SELECT'
WHERE data_type = 'TEXT' AND attribute_key = 'grade'
  AND category_id IN (SELECT id FROM categories WHERE slug = 'school-tuition');

-- ============================================================================
-- 2. Curriculum corrections on School Tuition (only place curriculum exists): required -> false,
--    label/display_order corrections. Stable values (LOCAL, EDEXCEL, CAMBRIDGE, IB, PROFESSIONAL)
--    are preserved so existing ad_attribute_values keep resolving.
-- ============================================================================
UPDATE attribute_definitions SET required = false
WHERE attribute_key = 'curriculum' AND required = true
  AND category_id IN (SELECT id FROM categories WHERE slug = 'school-tuition');

UPDATE attribute_options SET label = 'Sri Lankan National', display_order = 10
WHERE option_value = 'LOCAL' AND attribute_definition_id IN (
    SELECT d.id FROM attribute_definitions d JOIN categories c ON c.id = d.category_id
    WHERE c.slug = 'school-tuition' AND d.attribute_key = 'curriculum');
UPDATE attribute_options SET display_order = 20
WHERE option_value = 'CAMBRIDGE' AND attribute_definition_id IN (
    SELECT d.id FROM attribute_definitions d JOIN categories c ON c.id = d.category_id
    WHERE c.slug = 'school-tuition' AND d.attribute_key = 'curriculum');
UPDATE attribute_options SET label = 'Pearson Edexcel', display_order = 30
WHERE option_value = 'EDEXCEL' AND attribute_definition_id IN (
    SELECT d.id FROM attribute_definitions d JOIN categories c ON c.id = d.category_id
    WHERE c.slug = 'school-tuition' AND d.attribute_key = 'curriculum');
UPDATE attribute_options SET display_order = 40
WHERE option_value = 'IB' AND attribute_definition_id IN (
    SELECT d.id FROM attribute_definitions d JOIN categories c ON c.id = d.category_id
    WHERE c.slug = 'school-tuition' AND d.attribute_key = 'curriculum');
UPDATE attribute_options SET display_order = 50
WHERE option_value = 'PROFESSIONAL' AND attribute_definition_id IN (
    SELECT d.id FROM attribute_definitions d JOIN categories c ON c.id = d.category_id
    WHERE c.slug = 'school-tuition' AND d.attribute_key = 'curriculum');

-- Medium (SINHALA/ENGLISH/TAMIL) already correct - no changes.

-- ============================================================================
-- 3. New attribute definitions for the categories that don't yet have subject/grade/classMode.
-- ============================================================================
INSERT INTO attribute_definitions (category_id, attribute_key, name, data_type, required, filterable, searchable, unit, display_order, active, created_at, updated_at) SELECT c.id, 'subject', 'Subject', 'SELECT', 't', 't', 't', NULL, 10, 't', now(), now() FROM categories c WHERE c.slug = 'higher-education' AND NOT EXISTS (SELECT 1 FROM attribute_definitions WHERE category_id = c.id AND attribute_key = 'subject');
INSERT INTO attribute_definitions (category_id, attribute_key, name, data_type, required, filterable, searchable, unit, display_order, active, created_at, updated_at) SELECT c.id, 'grade', 'Grade / Level', 'SELECT', 'f', 't', 't', NULL, 20, 't', now(), now() FROM categories c WHERE c.slug = 'higher-education' AND NOT EXISTS (SELECT 1 FROM attribute_definitions WHERE category_id = c.id AND attribute_key = 'grade');
INSERT INTO attribute_definitions (category_id, attribute_key, name, data_type, required, filterable, searchable, unit, display_order, active, created_at, updated_at) SELECT c.id, 'classMode', 'Class Mode', 'SELECT', 't', 't', 'f', NULL, 30, 't', now(), now() FROM categories c WHERE c.slug = 'higher-education' AND NOT EXISTS (SELECT 1 FROM attribute_definitions WHERE category_id = c.id AND attribute_key = 'classMode');

INSERT INTO attribute_definitions (category_id, attribute_key, name, data_type, required, filterable, searchable, unit, display_order, active, created_at, updated_at) SELECT c.id, 'subject', 'Subject', 'SELECT', 't', 't', 't', NULL, 10, 't', now(), now() FROM categories c WHERE c.slug = 'language-classes' AND NOT EXISTS (SELECT 1 FROM attribute_definitions WHERE category_id = c.id AND attribute_key = 'subject');
INSERT INTO attribute_definitions (category_id, attribute_key, name, data_type, required, filterable, searchable, unit, display_order, active, created_at, updated_at) SELECT c.id, 'classMode', 'Class Mode', 'SELECT', 't', 't', 'f', NULL, 20, 't', now(), now() FROM categories c WHERE c.slug = 'language-classes' AND NOT EXISTS (SELECT 1 FROM attribute_definitions WHERE category_id = c.id AND attribute_key = 'classMode');

INSERT INTO attribute_definitions (category_id, attribute_key, name, data_type, required, filterable, searchable, unit, display_order, active, created_at, updated_at) SELECT c.id, 'subject', 'Subject', 'SELECT', 't', 't', 't', NULL, 10, 't', now(), now() FROM categories c WHERE c.slug = 'professional-courses' AND NOT EXISTS (SELECT 1 FROM attribute_definitions WHERE category_id = c.id AND attribute_key = 'subject');
INSERT INTO attribute_definitions (category_id, attribute_key, name, data_type, required, filterable, searchable, unit, display_order, active, created_at, updated_at) SELECT c.id, 'grade', 'Grade / Level', 'SELECT', 'f', 't', 't', NULL, 20, 't', now(), now() FROM categories c WHERE c.slug = 'professional-courses' AND NOT EXISTS (SELECT 1 FROM attribute_definitions WHERE category_id = c.id AND attribute_key = 'grade');
INSERT INTO attribute_definitions (category_id, attribute_key, name, data_type, required, filterable, searchable, unit, display_order, active, created_at, updated_at) SELECT c.id, 'classMode', 'Class Mode', 'SELECT', 't', 't', 'f', NULL, 30, 't', now(), now() FROM categories c WHERE c.slug = 'professional-courses' AND NOT EXISTS (SELECT 1 FROM attribute_definitions WHERE category_id = c.id AND attribute_key = 'classMode');

INSERT INTO attribute_definitions (category_id, attribute_key, name, data_type, required, filterable, searchable, unit, display_order, active, created_at, updated_at) SELECT c.id, 'subject', 'Subject', 'SELECT', 't', 't', 't', NULL, 10, 't', now(), now() FROM categories c WHERE c.slug = 'other-education-tuition' AND NOT EXISTS (SELECT 1 FROM attribute_definitions WHERE category_id = c.id AND attribute_key = 'subject');
INSERT INTO attribute_definitions (category_id, attribute_key, name, data_type, required, filterable, searchable, unit, display_order, active, created_at, updated_at) SELECT c.id, 'classMode', 'Class Mode', 'SELECT', 't', 't', 'f', NULL, 20, 't', now(), now() FROM categories c WHERE c.slug = 'other-education-tuition' AND NOT EXISTS (SELECT 1 FROM attribute_definitions WHERE category_id = c.id AND attribute_key = 'classMode');

-- Technology & Coding gets a grade/level definition too (see task example: Programming level can
-- be PROFESSIONAL or unset) - classMode's display_order shifts from 20 to 30 to make room.
INSERT INTO attribute_definitions (category_id, attribute_key, name, data_type, required, filterable, searchable, unit, display_order, active, created_at, updated_at) SELECT c.id, 'grade', 'Grade / Level', 'SELECT', 'f', 't', 't', NULL, 20, 't', now(), now() FROM categories c WHERE c.slug = 'technology-coding' AND NOT EXISTS (SELECT 1 FROM attribute_definitions WHERE category_id = c.id AND attribute_key = 'grade');
UPDATE attribute_definitions SET display_order = 30
WHERE attribute_key = 'classMode' AND display_order = 20
  AND category_id IN (SELECT id FROM categories WHERE slug = 'technology-coding');

-- ============================================================================
-- 4. Level (grade) options - identical canonical set on every category that has a grade
--    definition (School Tuition, Higher Education, Professional Courses, Technology & Coding).
--    Not added to Music/Dancing/Drama & Theatre/Art & Creative Classes/Language Classes/Other
--    Education & Tuition - level does not apply there (kept optional/absent, per the task's own
--    examples).
-- ============================================================================
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'PRIMARY', 'Primary', 10, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'school-tuition' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'PRIMARY');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'GRADE_6_9', 'Grade 6-9', 20, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'school-tuition' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'GRADE_6_9');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'OL', 'O/L', 30, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'school-tuition' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'OL');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'AL', 'A/L', 40, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'school-tuition' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'AL');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'IGCSE', 'IGCSE', 50, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'school-tuition' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'IGCSE');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'AS_LEVEL', 'AS Level', 60, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'school-tuition' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'AS_LEVEL');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'A_LEVEL', 'A Level', 70, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'school-tuition' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'A_LEVEL');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'UNIVERSITY', 'University', 80, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'school-tuition' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'UNIVERSITY');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'PROFESSIONAL', 'Professional', 90, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'school-tuition' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'PROFESSIONAL');

INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'PRIMARY', 'Primary', 10, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'higher-education' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'PRIMARY');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'GRADE_6_9', 'Grade 6-9', 20, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'higher-education' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'GRADE_6_9');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'OL', 'O/L', 30, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'higher-education' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'OL');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'AL', 'A/L', 40, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'higher-education' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'AL');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'IGCSE', 'IGCSE', 50, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'higher-education' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'IGCSE');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'AS_LEVEL', 'AS Level', 60, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'higher-education' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'AS_LEVEL');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'A_LEVEL', 'A Level', 70, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'higher-education' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'A_LEVEL');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'UNIVERSITY', 'University', 80, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'higher-education' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'UNIVERSITY');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'PROFESSIONAL', 'Professional', 90, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'higher-education' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'PROFESSIONAL');

INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'PRIMARY', 'Primary', 10, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'professional-courses' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'PRIMARY');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'GRADE_6_9', 'Grade 6-9', 20, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'professional-courses' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'GRADE_6_9');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'OL', 'O/L', 30, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'professional-courses' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'OL');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'AL', 'A/L', 40, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'professional-courses' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'AL');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'IGCSE', 'IGCSE', 50, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'professional-courses' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'IGCSE');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'AS_LEVEL', 'AS Level', 60, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'professional-courses' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'AS_LEVEL');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'A_LEVEL', 'A Level', 70, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'professional-courses' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'A_LEVEL');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'UNIVERSITY', 'University', 80, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'professional-courses' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'UNIVERSITY');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'PROFESSIONAL', 'Professional', 90, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'professional-courses' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'PROFESSIONAL');

INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'PRIMARY', 'Primary', 10, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'technology-coding' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'PRIMARY');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'GRADE_6_9', 'Grade 6-9', 20, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'technology-coding' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'GRADE_6_9');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'OL', 'O/L', 30, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'technology-coding' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'OL');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'AL', 'A/L', 40, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'technology-coding' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'AL');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'IGCSE', 'IGCSE', 50, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'technology-coding' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'IGCSE');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'AS_LEVEL', 'AS Level', 60, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'technology-coding' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'AS_LEVEL');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'A_LEVEL', 'A Level', 70, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'technology-coding' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'A_LEVEL');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'UNIVERSITY', 'University', 80, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'technology-coding' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'UNIVERSITY');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'PROFESSIONAL', 'Professional', 90, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'technology-coding' AND d.attribute_key = 'grade' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'PROFESSIONAL');

-- ============================================================================
-- 5. Subject options - scoped per category to what's actually relevant there (not every subject
--    on every category), matching the task's own category -> subject groupings/examples.
-- ============================================================================

-- School Tuition: academic subjects, plus Spoken English/IELTS since existing seed ads already
-- use this category for them (Language Classes carries the primary language-learning list below).
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'MATHEMATICS', 'Mathematics', 10, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'school-tuition' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'MATHEMATICS');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'COMBINED_MATHEMATICS', 'Combined Mathematics', 20, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'school-tuition' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'COMBINED_MATHEMATICS');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'SCIENCE', 'Science', 30, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'school-tuition' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'SCIENCE');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'PHYSICS', 'Physics', 40, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'school-tuition' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'PHYSICS');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'CHEMISTRY', 'Chemistry', 50, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'school-tuition' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'CHEMISTRY');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'BIOLOGY', 'Biology', 60, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'school-tuition' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'BIOLOGY');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'ENGLISH', 'English', 70, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'school-tuition' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'ENGLISH');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'ENGLISH_LITERATURE', 'English Literature', 80, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'school-tuition' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'ENGLISH_LITERATURE');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'SINHALA', 'Sinhala', 90, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'school-tuition' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'SINHALA');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'TAMIL', 'Tamil', 100, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'school-tuition' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'TAMIL');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'ICT', 'ICT', 110, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'school-tuition' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'ICT');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'ACCOUNTING', 'Accounting', 120, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'school-tuition' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'ACCOUNTING');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'BUSINESS_STUDIES', 'Business Studies', 130, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'school-tuition' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'BUSINESS_STUDIES');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'ECONOMICS', 'Economics', 140, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'school-tuition' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'ECONOMICS');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'HISTORY', 'History', 150, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'school-tuition' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'HISTORY');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'GEOGRAPHY', 'Geography', 160, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'school-tuition' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'GEOGRAPHY');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'CIVIC_EDUCATION', 'Civic Education', 170, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'school-tuition' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'CIVIC_EDUCATION');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'COMMERCE', 'Commerce', 180, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'school-tuition' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'COMMERCE');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'SPOKEN_ENGLISH', 'Spoken English', 190, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'school-tuition' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'SPOKEN_ENGLISH');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'IELTS', 'IELTS', 200, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'school-tuition' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'IELTS');

-- Higher Education: same academic list as School Tuition (advanced/university-level tutoring in
-- the same subjects).
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'MATHEMATICS', 'Mathematics', 10, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'higher-education' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'MATHEMATICS');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'COMBINED_MATHEMATICS', 'Combined Mathematics', 20, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'higher-education' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'COMBINED_MATHEMATICS');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'SCIENCE', 'Science', 30, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'higher-education' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'SCIENCE');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'PHYSICS', 'Physics', 40, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'higher-education' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'PHYSICS');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'CHEMISTRY', 'Chemistry', 50, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'higher-education' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'CHEMISTRY');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'BIOLOGY', 'Biology', 60, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'higher-education' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'BIOLOGY');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'ENGLISH', 'English', 70, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'higher-education' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'ENGLISH');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'ENGLISH_LITERATURE', 'English Literature', 80, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'higher-education' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'ENGLISH_LITERATURE');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'SINHALA', 'Sinhala', 90, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'higher-education' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'SINHALA');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'TAMIL', 'Tamil', 100, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'higher-education' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'TAMIL');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'ICT', 'ICT', 110, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'higher-education' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'ICT');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'ACCOUNTING', 'Accounting', 120, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'higher-education' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'ACCOUNTING');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'BUSINESS_STUDIES', 'Business Studies', 130, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'higher-education' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'BUSINESS_STUDIES');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'ECONOMICS', 'Economics', 140, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'higher-education' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'ECONOMICS');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'HISTORY', 'History', 150, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'higher-education' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'HISTORY');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'GEOGRAPHY', 'Geography', 160, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'higher-education' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'GEOGRAPHY');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'CIVIC_EDUCATION', 'Civic Education', 170, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'higher-education' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'CIVIC_EDUCATION');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'COMMERCE', 'Commerce', 180, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'higher-education' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'COMMERCE');

-- Language Classes: dedicated language-learning subjects.
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'SPOKEN_ENGLISH', 'Spoken English', 10, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'language-classes' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'SPOKEN_ENGLISH');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'IELTS', 'IELTS', 20, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'language-classes' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'IELTS');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'FRENCH', 'French', 30, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'language-classes' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'FRENCH');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'GERMAN', 'German', 40, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'language-classes' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'GERMAN');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'JAPANESE', 'Japanese', 50, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'language-classes' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'JAPANESE');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'KOREAN', 'Korean', 60, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'language-classes' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'KOREAN');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'CHINESE', 'Chinese', 70, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'language-classes' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'CHINESE');

-- Professional Courses: vocational/commerce subjects (shared canonical values with School
-- Tuition/Higher Education - dual-purpose subjects, not a new concept).
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'ACCOUNTING', 'Accounting', 10, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'professional-courses' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'ACCOUNTING');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'BUSINESS_STUDIES', 'Business Studies', 20, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'professional-courses' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'BUSINESS_STUDIES');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'ECONOMICS', 'Economics', 30, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'professional-courses' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'ECONOMICS');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'COMMERCE', 'Commerce', 40, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'professional-courses' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'COMMERCE');

-- Music.
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'MUSIC', 'Music', 10, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'music' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'MUSIC');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'PIANO', 'Piano', 20, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'music' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'PIANO');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'GUITAR', 'Guitar', 30, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'music' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'GUITAR');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'VIOLIN', 'Violin', 40, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'music' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'VIOLIN');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'DRUMS', 'Drums', 50, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'music' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'DRUMS');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'SINGING', 'Singing', 60, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'music' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'SINGING');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'EASTERN_MUSIC', 'Eastern Music', 70, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'music' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'EASTERN_MUSIC');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'WESTERN_MUSIC', 'Western Music', 80, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'music' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'WESTERN_MUSIC');

-- Dancing.
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'KANDYAN_DANCING', 'Kandyan Dancing', 10, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'dancing' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'KANDYAN_DANCING');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'BHARATANATYAM', 'Bharatanatyam', 20, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'dancing' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'BHARATANATYAM');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'WESTERN_DANCING', 'Western Dancing', 30, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'dancing' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'WESTERN_DANCING');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'BALLET', 'Ballet', 40, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'dancing' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'BALLET');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'HIP_HOP', 'Hip Hop', 50, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'dancing' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'HIP_HOP');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'CONTEMPORARY_DANCING', 'Contemporary Dancing', 60, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'dancing' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'CONTEMPORARY_DANCING');

-- Drama & Theatre.
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'ACTING', 'Acting', 10, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'drama-theatre' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'ACTING');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'SPEECH_AND_DRAMA', 'Speech & Drama', 20, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'drama-theatre' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'SPEECH_AND_DRAMA');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'THEATRE', 'Theatre', 30, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'drama-theatre' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'THEATRE');

-- Art & Creative Classes.
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'ART', 'Art', 10, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'art-creative-classes' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'ART');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'DRAWING', 'Drawing', 20, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'art-creative-classes' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'DRAWING');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'PAINTING', 'Painting', 30, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'art-creative-classes' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'PAINTING');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'PHOTOGRAPHY', 'Photography', 40, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'art-creative-classes' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'PHOTOGRAPHY');

-- Technology & Coding.
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'CODING', 'Coding', 10, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'technology-coding' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'CODING');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'PROGRAMMING', 'Programming', 20, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'technology-coding' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'PROGRAMMING');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'ROBOTICS', 'Robotics', 30, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'technology-coding' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'ROBOTICS');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'WEB_DEVELOPMENT', 'Web Development', 40, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'technology-coding' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'WEB_DEVELOPMENT');

-- Other Education & Tuition: Chess, Karate, Swimming (per task examples - valid non-academic
-- learning domains that don't fit the main categories).
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'CHESS', 'Chess', 10, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'other-education-tuition' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'CHESS');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'KARATE', 'Karate', 20, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'other-education-tuition' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'KARATE');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'SWIMMING', 'Swimming', 30, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'other-education-tuition' AND d.attribute_key = 'subject' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'SWIMMING');

-- ============================================================================
-- 6. Delivery mode (classMode): add HOME_VISIT to every existing classMode definition, and the
--    full 4-option set to the newly created ones. BOTH keeps its existing "Online & Physical"
--    label/value (Option A) - no existing ad using BOTH is affected.
-- ============================================================================
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'HOME_VISIT', 'Home Visit', 4, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'school-tuition' AND d.attribute_key = 'classMode' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'HOME_VISIT');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'HOME_VISIT', 'Home Visit', 4, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'music' AND d.attribute_key = 'classMode' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'HOME_VISIT');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'HOME_VISIT', 'Home Visit', 4, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'dancing' AND d.attribute_key = 'classMode' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'HOME_VISIT');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'HOME_VISIT', 'Home Visit', 4, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'drama-theatre' AND d.attribute_key = 'classMode' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'HOME_VISIT');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'HOME_VISIT', 'Home Visit', 4, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'art-creative-classes' AND d.attribute_key = 'classMode' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'HOME_VISIT');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'HOME_VISIT', 'Home Visit', 4, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'technology-coding' AND d.attribute_key = 'classMode' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'HOME_VISIT');

INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'PHYSICAL', 'Physical', 10, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'higher-education' AND d.attribute_key = 'classMode' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'PHYSICAL');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'ONLINE', 'Online', 20, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'higher-education' AND d.attribute_key = 'classMode' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'ONLINE');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'BOTH', 'Online & Physical', 30, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'higher-education' AND d.attribute_key = 'classMode' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'BOTH');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'HOME_VISIT', 'Home Visit', 40, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'higher-education' AND d.attribute_key = 'classMode' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'HOME_VISIT');

INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'PHYSICAL', 'Physical', 10, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'language-classes' AND d.attribute_key = 'classMode' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'PHYSICAL');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'ONLINE', 'Online', 20, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'language-classes' AND d.attribute_key = 'classMode' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'ONLINE');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'BOTH', 'Online & Physical', 30, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'language-classes' AND d.attribute_key = 'classMode' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'BOTH');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'HOME_VISIT', 'Home Visit', 40, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'language-classes' AND d.attribute_key = 'classMode' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'HOME_VISIT');

INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'PHYSICAL', 'Physical', 10, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'professional-courses' AND d.attribute_key = 'classMode' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'PHYSICAL');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'ONLINE', 'Online', 20, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'professional-courses' AND d.attribute_key = 'classMode' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'ONLINE');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'BOTH', 'Online & Physical', 30, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'professional-courses' AND d.attribute_key = 'classMode' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'BOTH');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'HOME_VISIT', 'Home Visit', 40, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'professional-courses' AND d.attribute_key = 'classMode' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'HOME_VISIT');

INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'PHYSICAL', 'Physical', 10, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'other-education-tuition' AND d.attribute_key = 'classMode' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'PHYSICAL');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'ONLINE', 'Online', 20, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'other-education-tuition' AND d.attribute_key = 'classMode' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'ONLINE');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'BOTH', 'Online & Physical', 30, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'other-education-tuition' AND d.attribute_key = 'classMode' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'BOTH');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'HOME_VISIT', 'Home Visit', 40, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'other-education-tuition' AND d.attribute_key = 'classMode' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'HOME_VISIT');
