-- Introduces a reusable promotion campaign concept: a temporary, channel-scoped price override
-- for one or more promotion_plans (e.g. a launch offer or a seasonal discount), stored separately
-- from promotion_plans.price so the plan's permanent base price is never overwritten by a
-- temporary offer. PromotionPricingService resolves the currently-effective price for a plan by
-- finding the campaign (if any) that is active, in-date, and mapped to that plan.
--
-- Two pricing shapes are supported (see ck_promotion_campaigns_pricing_fields): FIXED_PRICE (an
-- exact charged price, e.g. "Rs. 990 for everything") and PERCENTAGE_DISCOUNT (a percentage off
-- the plan's base price, with an optional minimum_price floor so a cheap plan's discount can
-- never undercut a more important campaign price). A generic promotion-rule engine is
-- deliberately not attempted - just these two pricing types, matching the two campaigns known to
-- be needed at launch.
CREATE TABLE promotion_campaigns (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying(60) NOT NULL,
    name character varying(120) NOT NULL,
    description character varying(500) NOT NULL,
    source_channel character varying(20) NOT NULL,
    pricing_type character varying(20) NOT NULL,
    discount_percent numeric(5,2),
    fixed_price numeric(19,2),
    minimum_price numeric(19,2),
    active boolean NOT NULL DEFAULT true,
    starts_at timestamp(6) with time zone NOT NULL,
    ends_at timestamp(6) with time zone NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT uk_promotion_campaign_code UNIQUE (code),
    CONSTRAINT ck_promotion_campaigns_source_channel CHECK (source_channel IN ('MAIN_SITE', 'TUITION', 'BOARDING')),
    CONSTRAINT ck_promotion_campaigns_pricing_type CHECK (pricing_type IN ('FIXED_PRICE', 'PERCENTAGE_DISCOUNT')),
    CONSTRAINT ck_promotion_campaigns_pricing_fields CHECK (
        (pricing_type = 'FIXED_PRICE' AND fixed_price IS NOT NULL AND discount_percent IS NULL) OR
        (pricing_type = 'PERCENTAGE_DISCOUNT' AND discount_percent IS NOT NULL AND fixed_price IS NULL)
    ),
    CONSTRAINT ck_promotion_campaigns_dates CHECK (ends_at > starts_at)
);

-- Which plans a campaign applies to. A campaign must be explicitly mapped to each eligible plan
-- (never "applies to everything in this channel" implicitly) so a future campaign can safely
-- target a single plan (e.g. only Search Boost) without affecting the rest of the catalog.
CREATE TABLE promotion_campaign_plans (
    campaign_id bigint NOT NULL REFERENCES promotion_campaigns(id),
    promotion_plan_id bigint NOT NULL REFERENCES promotion_plans(id),
    PRIMARY KEY (campaign_id, promotion_plan_id)
);
