-- Baseline schema derived from the current JPA entity model (com.slmanju.ceylonads.*.entity),
-- cross-checked against the live ceylonads_dev PostgreSQL schema. Table/column/constraint names
-- match the names already in use so this is a documentation of the current state, not a redesign.
--
-- Intentionally excluded vs. the live ceylonads_dev schema (obsolete, unmapped by any entity):
--   ads.location_id       - superseded by the normalized ad_locations join table.
--   media.url             - superseded by media.storage_key; public URLs are derived from config.
--   payments_payment_method_check - removed so PaymentMethod can evolve without DB drift.
-- V6 drops these from any pre-existing database being adopted; a fresh database never has them.

-- accounts: authentication identity shared by customers, admins and moderators.
CREATE TABLE accounts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username character varying(80) NOT NULL,
    email character varying(160) NOT NULL,
    password_hash character varying(255) NOT NULL,
    role character varying(20) NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT uk_account_username UNIQUE (username),
    CONSTRAINT uk_account_email UNIQUE (email),
    CONSTRAINT accounts_role_check CHECK (role IN ('CUSTOMER', 'MODERATOR', 'ADMIN')),
    CONSTRAINT accounts_status_check CHECK (status IN ('ACTIVE', 'SUSPENDED', 'DISABLED'))
);

-- locations: self-referencing province -> district -> city hierarchy.
CREATE TABLE locations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(120) NOT NULL,
    slug character varying(140) NOT NULL,
    type character varying(20) NOT NULL,
    parent_id bigint REFERENCES locations(id),
    active boolean NOT NULL DEFAULT true,
    CONSTRAINT uk_location_slug UNIQUE (slug),
    CONSTRAINT locations_type_check CHECK (type IN ('PROVINCE', 'DISTRICT', 'CITY'))
);

-- categories: self-referencing top-level -> leaf hierarchy.
CREATE TABLE categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(100) NOT NULL,
    slug character varying(120) NOT NULL,
    parent_id bigint REFERENCES categories(id),
    display_order integer NOT NULL,
    active boolean NOT NULL DEFAULT true,
    CONSTRAINT uk_category_slug UNIQUE (slug)
);

-- customers: seller/buyer profile, one per account.
CREATE TABLE customers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id bigint NOT NULL REFERENCES accounts(id),
    display_name character varying(120) NOT NULL,
    phone character varying(30),
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT uk_customer_account UNIQUE (account_id)
);

-- attribute_definitions: per-leaf-category dynamic attribute metadata.
CREATE TABLE attribute_definitions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id bigint NOT NULL REFERENCES categories(id),
    attribute_key character varying(60) NOT NULL,
    name character varying(100) NOT NULL,
    data_type character varying(20) NOT NULL,
    required boolean NOT NULL,
    filterable boolean NOT NULL,
    searchable boolean NOT NULL,
    unit character varying(30),
    display_order integer NOT NULL,
    active boolean NOT NULL DEFAULT true,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT uk_attribute_definition_category_key UNIQUE (category_id, attribute_key),
    CONSTRAINT attribute_definitions_data_type_check
        CHECK (data_type IN ('TEXT', 'NUMBER', 'DECIMAL', 'BOOLEAN', 'SELECT', 'MULTI_SELECT'))
);

-- attribute_options: allowed values for SELECT / MULTI_SELECT attribute definitions.
CREATE TABLE attribute_options (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attribute_definition_id bigint NOT NULL REFERENCES attribute_definitions(id),
    option_value character varying(60) NOT NULL,
    label character varying(100) NOT NULL,
    display_order integer NOT NULL,
    active boolean NOT NULL DEFAULT true,
    CONSTRAINT uk_attribute_option_definition_value UNIQUE (attribute_definition_id, option_value)
);

-- promotion_slots: placements ads/banners can be promoted into.
CREATE TABLE promotion_slots (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying(60) NOT NULL,
    name character varying(120) NOT NULL,
    description character varying(500) NOT NULL,
    placement_type character varying(30) NOT NULL,
    category_id bigint REFERENCES categories(id),
    capacity integer NOT NULL,
    visible_count integer NOT NULL,
    display_order integer NOT NULL,
    active boolean NOT NULL DEFAULT true,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT uk_promotion_slot_code UNIQUE (code),
    CONSTRAINT promotion_slots_placement_type_check CHECK (placement_type IN
        ('HOME_FEATURED', 'HOME_BANNER', 'CATEGORY_FEATURED', 'CATEGORY_BANNER', 'TOP_SEARCH', 'AD_DETAIL_SIDEBAR'))
);

-- promotion_plans: sellable/configured plans, each bound to exactly one slot.
CREATE TABLE promotion_plans (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying(60) NOT NULL,
    name character varying(120) NOT NULL,
    description character varying(500) NOT NULL,
    promotion_slot_id bigint NOT NULL REFERENCES promotion_slots(id),
    duration_days integer NOT NULL,
    price numeric(19,2) NOT NULL,
    active boolean NOT NULL DEFAULT true,
    payment_required boolean NOT NULL,
    approval_required boolean NOT NULL,
    display_order integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT uk_promotion_plan_code UNIQUE (code)
);

-- ads: the classified listing itself.
CREATE TABLE ads (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title character varying(180) NOT NULL,
    description character varying(5000) NOT NULL,
    price numeric(19,2) NOT NULL,
    category_id bigint NOT NULL REFERENCES categories(id),
    seller_id bigint NOT NULL REFERENCES customers(id),
    status character varying(30) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    published_at timestamp(6) with time zone,
    reviewed_at timestamp(6) with time zone,
    reviewed_by_account_id bigint REFERENCES accounts(id),
    contact_name character varying(120),
    phone_number character varying(30),
    whatsapp_number character varying(30),
    CONSTRAINT ads_status_check CHECK (status IN
        ('DRAFT', 'PENDING_REVIEW', 'ACTIVE', 'REJECTED', 'SOLD', 'EXPIRED', 'DEACTIVATED')),
    CONSTRAINT ck_ads_price_non_negative CHECK (price >= 0)
);
CREATE INDEX idx_ads_status_created ON ads (status, created_at);
CREATE INDEX idx_ads_category ON ads (category_id);
CREATE INDEX idx_ads_seller ON ads (seller_id);

-- ad_attribute_values: typed attribute values per ad; MULTI_SELECT stores one row per value.
CREATE TABLE ad_attribute_values (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ad_id bigint NOT NULL REFERENCES ads(id),
    attribute_definition_id bigint NOT NULL REFERENCES attribute_definitions(id),
    value_text character varying(255),
    value_number numeric(19,4),
    value_boolean boolean,
    CONSTRAINT uk_ad_attribute_value UNIQUE (ad_id, attribute_definition_id, value_text)
);
CREATE INDEX idx_ad_attribute_values_ad ON ad_attribute_values (ad_id);
CREATE INDEX idx_ad_attribute_values_def_text ON ad_attribute_values (attribute_definition_id, value_text);
CREATE INDEX idx_ad_attribute_values_def_number ON ad_attribute_values (attribute_definition_id, value_number);

-- ad_locations: normalized Ad -> 0..N Locations relationship.
CREATE TABLE ad_locations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ad_id bigint NOT NULL REFERENCES ads(id) ON DELETE CASCADE,
    location_id bigint NOT NULL REFERENCES locations(id),
    CONSTRAINT uk_ad_location UNIQUE (ad_id, location_id)
);
CREATE INDEX idx_ad_locations_ad ON ad_locations (ad_id);
CREATE INDEX idx_ad_locations_location ON ad_locations (location_id);

-- media: uploaded images, keyed by storage_key; public URLs are derived from config, not stored.
CREATE TABLE media (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ad_id bigint REFERENCES ads(id),
    owner_type character varying(30) NOT NULL,
    storage_key character varying(200) NOT NULL,
    content_type character varying(100) NOT NULL,
    display_order integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT media_owner_type_check CHECK (owner_type IN ('AD', 'PAYMENT_RECEIPT', 'PROMOTION_BANNER'))
);

-- promotions: an active/pending promotion of either an ad or a standalone banner.
CREATE TABLE promotions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind character varying(20) NOT NULL,
    ad_id bigint REFERENCES ads(id),
    customer_id bigint NOT NULL REFERENCES customers(id),
    promotion_plan_id bigint NOT NULL REFERENCES promotion_plans(id),
    status character varying(30) NOT NULL,
    price_amount numeric(19,2) NOT NULL,
    duration_days integer NOT NULL,
    banner_media_id bigint REFERENCES media(id),
    target_url character varying(500),
    payment_waived boolean NOT NULL DEFAULT false,
    starts_at timestamp(6) with time zone,
    ends_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT promotions_kind_check CHECK (kind IN ('AD_PROMOTION', 'BANNER_PROMOTION')),
    CONSTRAINT promotions_status_check CHECK (status IN
        ('PENDING_PAYMENT', 'PENDING_APPROVAL', 'SCHEDULED', 'ACTIVE', 'EXPIRED', 'CANCELLED')),
    CONSTRAINT ck_promotions_kind_owner CHECK (
        (kind = 'AD_PROMOTION' AND ad_id IS NOT NULL AND banner_media_id IS NULL) OR
        (kind = 'BANNER_PROMOTION' AND banner_media_id IS NOT NULL AND ad_id IS NULL)
    )
);
CREATE INDEX idx_promotions_status_ends ON promotions (status, ends_at);
CREATE INDEX idx_promotions_customer ON promotions (customer_id);
CREATE INDEX idx_promotions_ad ON promotions (ad_id);

-- payments: one payment per promotion (manual bank-transfer review flow).
CREATE TABLE payments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotion_id bigint NOT NULL REFERENCES promotions(id),
    customer_id bigint NOT NULL REFERENCES customers(id),
    payment_reference character varying(40) NOT NULL,
    amount numeric(19,2) NOT NULL,
    payment_method character varying(30) NOT NULL,
    status character varying(20) NOT NULL,
    bank_reference character varying(100),
    receipt_media_id bigint REFERENCES media(id),
    customer_note character varying(500),
    admin_note character varying(500),
    submitted_at timestamp(6) with time zone,
    reviewed_at timestamp(6) with time zone,
    reviewed_by_account_id bigint REFERENCES accounts(id),
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT uk_payment_promotion UNIQUE (promotion_id),
    CONSTRAINT uk_payment_reference UNIQUE (payment_reference),
    CONSTRAINT payments_status_check CHECK (status IN ('PENDING', 'SUBMITTED', 'APPROVED', 'REJECTED', 'CANCELLED'))
);
CREATE INDEX idx_payments_status ON payments (status);
CREATE INDEX idx_payments_customer ON payments (customer_id);
