-- Tuition-only public feedback/suggestion inbox (ezClass "Suggest" page). Deliberately its own
-- table rather than reusing ads/payments - a suggestion has no seller, category, or lifecycle in
-- common with those domains.
CREATE TABLE tuition_suggestions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120),
    email VARCHAR(180),
    phone VARCHAR(30),
    message VARCHAR(2000) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'NEW',
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    reviewed_at TIMESTAMP(6) WITH TIME ZONE,
    reviewed_by_account_id BIGINT
);

-- Backs the admin inbox list (NEW first, then REVIEWED, then CLOSED) and the dashboard's
-- "New Suggestions" count.
CREATE INDEX idx_tuition_suggestions_status_created ON tuition_suggestions (status, created_at);
