-- Add "Clothing" and "Machinery & Equipment" as new top-level categories.
--
-- 'clothing' already existed as a leaf under 'fashion-beauty', and 'industrial-machinery'
-- already existed as a leaf under 'business-industry'. Slugs are globally unique
-- (uk_category_slug), so rather than duplicate those concepts under new slugs, this migration
-- reparents the existing rows (same id/slug preserved) to their new top-level position instead
-- of inserting duplicates. 'shoes-footwear' and 'bags-accessories' are reparented the same way
-- since they were listed as Clothing's own children under 'fashion-beauty'. An "Agricultural
-- Machinery" child was intentionally NOT added under Machinery & Equipment because it duplicates
-- the existing 'agricultural-equipment' category under 'agriculture'.

-- New top-level category (Clothing is reparented below rather than inserted, since it already exists)
INSERT INTO categories (name, slug, parent_id, display_order, active) SELECT 'Machinery & Equipment', 'machinery-equipment', NULL, 170, 't' WHERE NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'machinery-equipment');

-- Reparent pre-existing categories to their new top-level position
UPDATE categories SET parent_id = NULL, display_order = 160 WHERE slug = 'clothing' AND parent_id IS NOT NULL;
UPDATE categories SET parent_id = (SELECT id FROM categories WHERE slug = 'clothing'), display_order = 40 WHERE slug = 'shoes-footwear';
UPDATE categories SET parent_id = (SELECT id FROM categories WHERE slug = 'clothing'), display_order = 50 WHERE slug = 'bags-accessories';
UPDATE categories SET parent_id = (SELECT id FROM categories WHERE slug = 'machinery-equipment'), display_order = 10 WHERE slug = 'industrial-machinery';

-- New Clothing children
INSERT INTO categories (name, slug, parent_id, display_order, active) SELECT 'Men''s Clothing', 'mens-clothing', p.id, 10, 't' FROM categories p WHERE p.slug = 'clothing' AND NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'mens-clothing');
INSERT INTO categories (name, slug, parent_id, display_order, active) SELECT 'Women''s Clothing', 'womens-clothing', p.id, 20, 't' FROM categories p WHERE p.slug = 'clothing' AND NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'womens-clothing');
INSERT INTO categories (name, slug, parent_id, display_order, active) SELECT 'Kids'' Clothing', 'kids-clothing', p.id, 30, 't' FROM categories p WHERE p.slug = 'clothing' AND NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'kids-clothing');
INSERT INTO categories (name, slug, parent_id, display_order, active) SELECT 'Watches & Jewellery', 'watches-jewellery', p.id, 60, 't' FROM categories p WHERE p.slug = 'clothing' AND NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'watches-jewellery');
INSERT INTO categories (name, slug, parent_id, display_order, active) SELECT 'Uniforms', 'uniforms', p.id, 70, 't' FROM categories p WHERE p.slug = 'clothing' AND NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'uniforms');
INSERT INTO categories (name, slug, parent_id, display_order, active) SELECT 'Traditional Clothing', 'traditional-clothing', p.id, 80, 't' FROM categories p WHERE p.slug = 'clothing' AND NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'traditional-clothing');
INSERT INTO categories (name, slug, parent_id, display_order, active) SELECT 'Other Clothing', 'other-clothing', p.id, 90, 't' FROM categories p WHERE p.slug = 'clothing' AND NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'other-clothing');

-- New Machinery & Equipment children
INSERT INTO categories (name, slug, parent_id, display_order, active) SELECT 'Construction Equipment', 'construction-equipment', p.id, 20, 't' FROM categories p WHERE p.slug = 'machinery-equipment' AND NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'construction-equipment');
INSERT INTO categories (name, slug, parent_id, display_order, active) SELECT 'Workshop Equipment', 'workshop-equipment', p.id, 30, 't' FROM categories p WHERE p.slug = 'machinery-equipment' AND NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'workshop-equipment');
INSERT INTO categories (name, slug, parent_id, display_order, active) SELECT 'Manufacturing Equipment', 'manufacturing-equipment', p.id, 40, 't' FROM categories p WHERE p.slug = 'machinery-equipment' AND NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'manufacturing-equipment');
INSERT INTO categories (name, slug, parent_id, display_order, active) SELECT 'Food Processing Equipment', 'food-processing-equipment', p.id, 50, 't' FROM categories p WHERE p.slug = 'machinery-equipment' AND NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'food-processing-equipment');
INSERT INTO categories (name, slug, parent_id, display_order, active) SELECT 'Generators', 'generators', p.id, 60, 't' FROM categories p WHERE p.slug = 'machinery-equipment' AND NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'generators');
INSERT INTO categories (name, slug, parent_id, display_order, active) SELECT 'Compressors', 'compressors', p.id, 70, 't' FROM categories p WHERE p.slug = 'machinery-equipment' AND NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'compressors');
INSERT INTO categories (name, slug, parent_id, display_order, active) SELECT 'Pumps', 'pumps', p.id, 80, 't' FROM categories p WHERE p.slug = 'machinery-equipment' AND NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'pumps');
INSERT INTO categories (name, slug, parent_id, display_order, active) SELECT 'Tools & Power Equipment', 'tools-power-equipment', p.id, 90, 't' FROM categories p WHERE p.slug = 'machinery-equipment' AND NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'tools-power-equipment');
INSERT INTO categories (name, slug, parent_id, display_order, active) SELECT 'Commercial Equipment', 'commercial-equipment', p.id, 100, 't' FROM categories p WHERE p.slug = 'machinery-equipment' AND NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'commercial-equipment');
INSERT INTO categories (name, slug, parent_id, display_order, active) SELECT 'Other Machinery & Equipment', 'other-machinery-equipment', p.id, 110, 't' FROM categories p WHERE p.slug = 'machinery-equipment' AND NOT EXISTS (SELECT 1 FROM categories WHERE slug = 'other-machinery-equipment');

-- Attribute definitions on the two new top-level categories. Filterable attributes are inherited
-- by descendant categories for search (see AttributeDefinitionService.findFiltersByCategorySlug),
-- so defining them once here covers all Clothing/Machinery children without a per-leaf attribute
-- model. 'brand' is free-text (TEXT) rather than a curated SELECT list, since clothing and
-- machinery brands are far more varied than the mobile-phones brand list.
INSERT INTO attribute_definitions (category_id, attribute_key, name, data_type, required, filterable, searchable, unit, display_order, active, created_at, updated_at) SELECT c.id, 'condition', 'Condition', 'SELECT', 'f', 't', 'f', NULL, 10, 't', now(), now() FROM categories c WHERE c.slug = 'clothing' AND NOT EXISTS (SELECT 1 FROM attribute_definitions WHERE category_id = c.id AND attribute_key = 'condition');
INSERT INTO attribute_definitions (category_id, attribute_key, name, data_type, required, filterable, searchable, unit, display_order, active, created_at, updated_at) SELECT c.id, 'gender', 'Gender', 'SELECT', 'f', 't', 'f', NULL, 20, 't', now(), now() FROM categories c WHERE c.slug = 'clothing' AND NOT EXISTS (SELECT 1 FROM attribute_definitions WHERE category_id = c.id AND attribute_key = 'gender');
INSERT INTO attribute_definitions (category_id, attribute_key, name, data_type, required, filterable, searchable, unit, display_order, active, created_at, updated_at) SELECT c.id, 'size', 'Size', 'SELECT', 'f', 't', 'f', NULL, 30, 't', now(), now() FROM categories c WHERE c.slug = 'clothing' AND NOT EXISTS (SELECT 1 FROM attribute_definitions WHERE category_id = c.id AND attribute_key = 'size');
INSERT INTO attribute_definitions (category_id, attribute_key, name, data_type, required, filterable, searchable, unit, display_order, active, created_at, updated_at) SELECT c.id, 'brand', 'Brand', 'TEXT', 'f', 't', 't', NULL, 40, 't', now(), now() FROM categories c WHERE c.slug = 'clothing' AND NOT EXISTS (SELECT 1 FROM attribute_definitions WHERE category_id = c.id AND attribute_key = 'brand');

INSERT INTO attribute_definitions (category_id, attribute_key, name, data_type, required, filterable, searchable, unit, display_order, active, created_at, updated_at) SELECT c.id, 'condition', 'Condition', 'SELECT', 'f', 't', 'f', NULL, 10, 't', now(), now() FROM categories c WHERE c.slug = 'machinery-equipment' AND NOT EXISTS (SELECT 1 FROM attribute_definitions WHERE category_id = c.id AND attribute_key = 'condition');
INSERT INTO attribute_definitions (category_id, attribute_key, name, data_type, required, filterable, searchable, unit, display_order, active, created_at, updated_at) SELECT c.id, 'brand', 'Brand', 'TEXT', 'f', 't', 't', NULL, 20, 't', now(), now() FROM categories c WHERE c.slug = 'machinery-equipment' AND NOT EXISTS (SELECT 1 FROM attribute_definitions WHERE category_id = c.id AND attribute_key = 'brand');
INSERT INTO attribute_definitions (category_id, attribute_key, name, data_type, required, filterable, searchable, unit, display_order, active, created_at, updated_at) SELECT c.id, 'model', 'Model', 'TEXT', 'f', 't', 't', NULL, 30, 't', now(), now() FROM categories c WHERE c.slug = 'machinery-equipment' AND NOT EXISTS (SELECT 1 FROM attribute_definitions WHERE category_id = c.id AND attribute_key = 'model');
INSERT INTO attribute_definitions (category_id, attribute_key, name, data_type, required, filterable, searchable, unit, display_order, active, created_at, updated_at) SELECT c.id, 'year', 'Year', 'NUMBER', 'f', 't', 'f', NULL, 40, 't', now(), now() FROM categories c WHERE c.slug = 'machinery-equipment' AND NOT EXISTS (SELECT 1 FROM attribute_definitions WHERE category_id = c.id AND attribute_key = 'year');
INSERT INTO attribute_definitions (category_id, attribute_key, name, data_type, required, filterable, searchable, unit, display_order, active, created_at, updated_at) SELECT c.id, 'power_source', 'Power Source', 'SELECT', 'f', 't', 'f', NULL, 50, 't', now(), now() FROM categories c WHERE c.slug = 'machinery-equipment' AND NOT EXISTS (SELECT 1 FROM attribute_definitions WHERE category_id = c.id AND attribute_key = 'power_source');

-- Attribute options
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'NEW', 'New', 1, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'clothing' AND d.attribute_key = 'condition' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'NEW');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'USED', 'Used', 2, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'clothing' AND d.attribute_key = 'condition' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'USED');

INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'MEN', 'Men', 1, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'clothing' AND d.attribute_key = 'gender' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'MEN');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'WOMEN', 'Women', 2, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'clothing' AND d.attribute_key = 'gender' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'WOMEN');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'KIDS', 'Kids', 3, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'clothing' AND d.attribute_key = 'gender' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'KIDS');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'UNISEX', 'Unisex', 4, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'clothing' AND d.attribute_key = 'gender' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'UNISEX');

INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'XS', 'XS', 1, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'clothing' AND d.attribute_key = 'size' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'XS');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'S', 'S', 2, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'clothing' AND d.attribute_key = 'size' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'S');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'M', 'M', 3, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'clothing' AND d.attribute_key = 'size' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'M');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'L', 'L', 4, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'clothing' AND d.attribute_key = 'size' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'L');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'XL', 'XL', 5, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'clothing' AND d.attribute_key = 'size' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'XL');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'XXL', 'XXL', 6, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'clothing' AND d.attribute_key = 'size' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'XXL');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'OTHER', 'Other', 7, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'clothing' AND d.attribute_key = 'size' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'OTHER');

INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'NEW', 'New', 1, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'machinery-equipment' AND d.attribute_key = 'condition' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'NEW');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'USED', 'Used', 2, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'machinery-equipment' AND d.attribute_key = 'condition' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'USED');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'RECONDITIONED', 'Reconditioned', 3, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'machinery-equipment' AND d.attribute_key = 'condition' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'RECONDITIONED');

INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'DIESEL', 'Diesel', 1, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'machinery-equipment' AND d.attribute_key = 'power_source' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'DIESEL');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'PETROL', 'Petrol', 2, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'machinery-equipment' AND d.attribute_key = 'power_source' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'PETROL');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'ELECTRIC', 'Electric', 3, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'machinery-equipment' AND d.attribute_key = 'power_source' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'ELECTRIC');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'MANUAL', 'Manual', 4, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'machinery-equipment' AND d.attribute_key = 'power_source' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'MANUAL');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'SOLAR', 'Solar', 5, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'machinery-equipment' AND d.attribute_key = 'power_source' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'SOLAR');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'OTHER', 'Other', 6, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'machinery-equipment' AND d.attribute_key = 'power_source' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'OTHER');
