-- Correct the Mobile Phones master data: storage options wrongly started at 64GB and were
-- required, and several major phone brands (Nokia among them) were missing from the brand list.
-- This is master-data/configuration only - no schema changes, no edits to already-applied
-- migrations, and no removal of existing options or values already used by ads.

-- Storage must be optional: a user should be able to post a phone ad without picking a capacity.
UPDATE attribute_definitions SET required = 'f', updated_at = now()
WHERE id = (SELECT d.id FROM attribute_definitions d JOIN categories c ON c.id = d.category_id
            WHERE c.slug = 'mobile-phones' AND d.attribute_key = 'storage')
  AND required = 't';

-- Renumber the existing storage options to make room for smaller capacities below 64GB. Option
-- values/ids are untouched, so ads already storing e.g. '128GB' remain valid - only display_order
-- changes.
UPDATE attribute_options SET display_order = 5 WHERE attribute_definition_id = (SELECT d.id FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'mobile-phones' AND d.attribute_key = 'storage') AND option_value = '64GB';
UPDATE attribute_options SET display_order = 6 WHERE attribute_definition_id = (SELECT d.id FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'mobile-phones' AND d.attribute_key = 'storage') AND option_value = '128GB';
UPDATE attribute_options SET display_order = 7 WHERE attribute_definition_id = (SELECT d.id FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'mobile-phones' AND d.attribute_key = 'storage') AND option_value = '256GB';
UPDATE attribute_options SET display_order = 8 WHERE attribute_definition_id = (SELECT d.id FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'mobile-phones' AND d.attribute_key = 'storage') AND option_value = '512GB';
UPDATE attribute_options SET display_order = 9 WHERE attribute_definition_id = (SELECT d.id FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'mobile-phones' AND d.attribute_key = 'storage') AND option_value = '1TB';

-- New smaller storage options. 4GB is included alongside 8GB/16GB/32GB because several of the
-- brands added below (Nokia, Infinix, Tecno, itel, Alcatel) sell entry-level Android phones
-- commonly shipping with 4-32GB of storage.
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, '4GB', '4 GB', 1, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'mobile-phones' AND d.attribute_key = 'storage' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = '4GB');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, '8GB', '8 GB', 2, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'mobile-phones' AND d.attribute_key = 'storage' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = '8GB');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, '16GB', '16 GB', 3, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'mobile-phones' AND d.attribute_key = 'storage' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = '16GB');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, '32GB', '32 GB', 4, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'mobile-phones' AND d.attribute_key = 'storage' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = '32GB');

-- Missing major phone brands. Existing brands (Apple, Samsung, Xiaomi, Huawei, OnePlus, Google,
-- Other) are left untouched - only genuinely absent brands are added, ordered after them and
-- before the existing 'Other' catch-all (display_order 99).
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'Redmi', 'Redmi', 7, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'mobile-phones' AND d.attribute_key = 'brand' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'Redmi');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'POCO', 'POCO', 8, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'mobile-phones' AND d.attribute_key = 'brand' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'POCO');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'Honor', 'Honor', 9, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'mobile-phones' AND d.attribute_key = 'brand' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'Honor');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'Nokia', 'Nokia', 10, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'mobile-phones' AND d.attribute_key = 'brand' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'Nokia');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'OPPO', 'OPPO', 11, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'mobile-phones' AND d.attribute_key = 'brand' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'OPPO');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'Vivo', 'Vivo', 12, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'mobile-phones' AND d.attribute_key = 'brand' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'Vivo');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'Realme', 'Realme', 13, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'mobile-phones' AND d.attribute_key = 'brand' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'Realme');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'Motorola', 'Motorola', 14, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'mobile-phones' AND d.attribute_key = 'brand' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'Motorola');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'Sony', 'Sony', 15, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'mobile-phones' AND d.attribute_key = 'brand' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'Sony');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'Nothing', 'Nothing', 16, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'mobile-phones' AND d.attribute_key = 'brand' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'Nothing');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'Infinix', 'Infinix', 17, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'mobile-phones' AND d.attribute_key = 'brand' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'Infinix');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'Tecno', 'Tecno', 18, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'mobile-phones' AND d.attribute_key = 'brand' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'Tecno');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'ZTE', 'ZTE', 19, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'mobile-phones' AND d.attribute_key = 'brand' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'ZTE');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'Asus', 'Asus', 20, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'mobile-phones' AND d.attribute_key = 'brand' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'Asus');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'Lenovo', 'Lenovo', 21, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'mobile-phones' AND d.attribute_key = 'brand' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'Lenovo');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'Alcatel', 'Alcatel', 22, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'mobile-phones' AND d.attribute_key = 'brand' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'Alcatel');
INSERT INTO attribute_options (attribute_definition_id, option_value, label, display_order, active) SELECT d.id, 'itel', 'itel', 23, 't' FROM attribute_definitions d JOIN categories c ON c.id = d.category_id WHERE c.slug = 'mobile-phones' AND d.attribute_key = 'brand' AND NOT EXISTS (SELECT 1 FROM attribute_options WHERE attribute_definition_id = d.id AND option_value = 'itel');
